VERSION 0.6

ARG repository=eniblock/2021-star-frontend

deps:
    FROM node:16-alpine
    RUN apk add fd
    WORKDIR /app
    ENV FORCE_COLOR=1
    COPY package.json package-lock.json ./
    RUN --mount=type=cache,target=/root/.npm \
        npm ci

dev:
    FROM +deps
    COPY . ./
    CMD npm start
    ARG tag=latest
    ARG ref=${repository}:${tag}
    SAVE IMAGE ${ref}

build:
    FROM +dev
    RUN npm run build-prod
    RUN fd '.*\.(js|css|html|svg|txt|gif|wasm)$' dist -x gzip -k
    SAVE ARTIFACT --keep-ts /app/dist
    # cache this target (including the layers from the target dependencies)
    ARG tag=latest
    SAVE IMAGE --cache-from=${repository}:cache-build-develop --push ${repository}:cache-build-${tag}

docker:
    FROM nginx:1-alpine
    COPY nginx.conf /etc/nginx/conf.d/default.conf
    COPY --keep-ts +build/dist/frontend /usr/share/nginx/html
    ARG tag=latest
    ARG ref=${repository}:${tag}
    ARG buildid=
    IF [ "${buildid}" = "" ]
        SAVE IMAGE --cache-from=${repository}:develop --push ${ref}
    ELSE
        SAVE IMAGE --cache-from=${repository}:develop --push ${ref} ${ref}.${buildid}
    END
