FROM registry.gitlab.com/xdev-tech/xdev-enterprise-business-network/keycloak:0.1.0
COPY themes/base/login/login.ftl /opt/bitnami/keycloak/themes/base/login/login.ftl
COPY themes/custom-theme /opt/bitnami/keycloak/themes/custom-theme/
COPY realm-config /realm-config/
