# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: orderer
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer1
        SANS:
          - 0.0.0.0
          - orderer1.orderer.testing.star.eniblock.fr
          - orderer1-hlf-ord.orderer-testing
      - Hostname: orderer2
        SANS:
          - 0.0.0.0
          - orderer2.orderer.testing.star.eniblock.fr
          - orderer2-hlf-ord.orderer-testing
      - Hostname: orderer3
        SANS:
          - 0.0.0.0
          - orderer3.orderer.testing.star.eniblock.fr
          - orderer3-hlf-ord.orderer-testing

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: enedis
    Domain: enedis
    EnableNodeOUs: true
    Specs:
      - Hostname: peer1
        SANS:
          - 0.0.0.0
          - peer1.enedis.testing.star.eniblock.fr
          - peer1-hlf-peer.enedis-testing
      - Hostname: peer2
        SANS:
          - 0.0.0.0
          - peer2.enedis.testing.star.eniblock.fr
          - peer2-hlf-peer.enedis-testing
    Users:
      Count: 1

  - Name: rte
    Domain: rte
    EnableNodeOUs: true
    Specs:
      - Hostname: peer1
        SANS:
          - 0.0.0.0
          - peer1.rte.testing.star.eniblock.fr
          - peer1-hlf-peer.rte-testing
      - Hostname: peer2
        SANS:
          - 0.0.0.0
          - peer2.rte.testing.star.eniblock.fr
          - peer2-hlf-peer.rte-testing
    Users:
      Count: 1

  - Name: producer
    Domain: producer
    EnableNodeOUs: true
    Specs:
      - Hostname: peer1
        SANS:
          - 0.0.0.0
          - peer1.producer.testing.star.eniblock.fr
          - peer1-hlf-peer.producer-testing
      - Hostname: peer2
        SANS:
          - 0.0.0.0
          - peer2.producer.testing.star.eniblock.fr
          - peer2-hlf-peer.producer-testing
    Users:
      Count: 1
