VERSION 0.6

deps:
    FROM node:16-alpine

    WORKDIR /app

    COPY package.json package-lock.json ./
    RUN npm ci

test:
    FROM +deps
    COPY . .
    ENV FORCE_COLOR=1
    RUN npm run test

docker:
    FROM +deps
    COPY . .
    RUN npm run build

    COPY META-INF /META-INF

    EXPOSE 9999

    ENV CHAINCODE_CONNECTION_ADDRESS=changeme:9999 \
        CHAINCODE_ADDRESS=0.0.0.0:9999 \
        CHAINCODE_NAME=star \
        CHAINCODE_LABEL=star

    CMD /ccid $CHAINCODE_CONNECTION_ADDRESS -l $CHAINCODE_LABEL -n $CHAINCODE_NAME -- sh -c '/app/node_modules/.bin/fabric-chaincode-node server --chaincode-address $CHAINCODE_ADDRESS --chaincode-id $CHAINCODE_ID'
    ARG tag=latest
    ARG ref=eniblock/2021-star-chaincode:${tag}
    SAVE IMAGE --push ${ref}
