apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-from-other-namespace
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: logging
      podSelector: {}
    - namespaceSelector:
        matchLabels:
          name: monitoring
      podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
