name: ci
on:
  push:
    branches:
      - "**"
      - "!prod"
    tags:
      - "*"

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  HELM_DIR: ./helm/star

jobs:

  ############################ tests ############################

  test-backend:
    runs-on: [self-hosted]
    steps:
    - uses: eniblock/build/actions/setup@4.1
    - run: earthly ./backend+test

  test-chaincode:
    runs-on: [self-hosted]
    steps:
    - uses: eniblock/build/actions/setup@4.1
    - run: earthly ./chaincode+test

  lint-helm:
    runs-on: [self-hosted]
    steps:
    - uses: eniblock/build/actions/setup@4.1
    - run: earthly ./helm+lint


  ############################ docker ############################

  docker-backend:
    runs-on: [self-hosted]
    needs: [test-backend, lint-helm, test-chaincode]
    steps:
    - uses: eniblock/build/actions/setup@4.1
    - run: earthly ./backend+docker --tag=${{ env.TAG }}

  docker-keycloak:
    runs-on: [self-hosted]
    needs: [test-backend, lint-helm, test-chaincode]
    steps:
    - uses: eniblock/build/actions/setup@4.1
    - run: earthly ./keycloak+docker --tag=${{ env.TAG }}

  docker-frontend:
    runs-on: [self-hosted]
    needs: [test-backend, lint-helm, test-chaincode]
    steps:
    - uses: eniblock/build/actions/setup@4.1
    - run: earthly ./frontend+docker --tag=${{ env.TAG }}

  docker-chaincode:
    runs-on: [self-hosted]
    needs: [test-backend, lint-helm, test-chaincode]
    steps:
    - uses: eniblock/build/actions/setup@4.1
    - run: earthly ./chaincode+docker --tag=${{ env.TAG }}

  ############################ helm ############################

  helm-publish:
    runs-on: [self-hosted]
    needs: [docker-backend, docker-keycloak, docker-frontend, docker-chaincode]
    steps:
    - uses: eniblock/build/actions/setup@4.1
    - name: Build/Publish the helm charts
      run: |
         earthly \
         --secret registry_password=${{ github.token }} \
         ./helm+publish \
         --tag=${{ env.TAG }}
    - name: Generate job summary
      run: |
        cat <<"EOF" >> $GITHUB_STEP_SUMMARY
        ## Helm package
        Helm package was generated with tag `${{ env.TAG }}`

        Use it directly with

        ~~~bash
        helm install star oci://ghcr.io/eniblock/star --version ${{ env.TAG }}
        ~~~
        EOF

  ############################ deploy ############################

  # testing

  deploy-enedis-testing:
    if: github.ref == 'refs/heads/develop'
    needs: [helm-publish]
    uses: './.github/workflows/deploy.yml'
    with:
      environment: enedis-testing
    secrets: inherit

  deploy-producer-testing:
    if: github.ref == 'refs/heads/develop'
    needs: [helm-publish]
    uses: './.github/workflows/deploy.yml'
    with:
      environment: producer-testing
    secrets: inherit

  deploy-rte-testing:
    if: github.ref == 'refs/heads/develop'
    needs: [helm-publish]
    uses: './.github/workflows/deploy.yml'
    with:
      environment: rte-testing
    secrets: inherit

  # staging

  deploy-enedis-staging:
    if: github.ref == 'refs/heads/staging'
    needs: [helm-publish]
    uses: './.github/workflows/deploy.yml'
    with:
      environment: enedis-staging
    secrets: inherit

  deploy-producer-staging:
    if: github.ref == 'refs/heads/staging'
    needs: [helm-publish]
    uses: './.github/workflows/deploy.yml'
    with:
      environment: producer-staging
    secrets: inherit

  deploy-rte-staging:
    if: github.ref == 'refs/heads/staging'
    needs: [helm-publish]
    uses: './.github/workflows/deploy.yml'
    with:
      environment: rte-staging
    secrets: inherit

  # see prod.yml for the prod environments
