name: deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}
    concurrency: ${{ inputs.environment }}
    steps:
    - uses: eniblock/build/actions/setup@4.1
      with:
        helmdir: helm/star
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
        raw_version_on_branch: prod
    - name: Update the application
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        KUBECONFIG2: ${{ secrets.KUBECONFIG2 }}
      run: |
        earthly \
          --secret dockerhub_token=${{ secrets.DOCKERHUB_TOKEN }} \
          --secret github_token=${{ secrets.GITHUB_TOKEN }} \
          --secret age_key=${{ secrets.AGE_KEY }} \
          --secret kubeconfig="$KUBECONFIG" \
          --secret kubeconfig2="$KUBECONFIG2" \
          ./helm+deploy \
          --environment ${{ inputs.environment }} \
          --tag ${{ env.TAG }}
    - name: Smoke tests
      run: |
        earthly \
          --secret test_username=${{ secrets.test_username}} \
          --secret test_password=${{ secrets.test_password }} \
          ./test/e2e/+smoke-${{ inputs.environment }}
