name: sonar
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - develop
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: [self-hosted]
    steps:
    - uses: eniblock/build/actions/setup@4.1
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
        fetch-depth: "0"
    - run: earthly +sonar
    - uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
