ingress:
  enabled: true
  host: "producer.staging.star.eniblock.fr"
backend:
  peerConnectionOrganization: producer
  instance: producer
keycloak:
  ingress:
    host: "producer.staging.star.eniblock.fr"
