global:
  dev: true

ingress:
  enabled: true
  host: "rte.localhost"

backend:
  peerConnectionOrganization: rte
  instance: tso
  # peerConnectionUser: Admin

keycloak:
  ingress:
    host: "rte.localhost"
  configurator:
    secrets:
      users:
        - username: userrte
          first_name: user
          last_name: rte
          email: userrte@star.com
          initial_password: kcuserrte

mail:
  dev: true
