global:
  dev: true

ingress:
  enabled: true
  host: "producer.localhost"

backend:
  peerConnectionOrganization: producer
  instance: producer

keycloak:
  ingress:
    host: "producer.localhost"
  credentials:
    secret:
  configurator:
    secrets:
      users:
        - username: userproducer
          first_name: user
          last_name: producer
          email: userproducer@star.com
          initial_password: kcuserproducer

mail:
  dev: true
