ingress:
  enabled: true
  host: "rte.testing.star.eniblock.fr"
backend:
  peerConnectionOrganization: rte
  instance: tso
keycloak:
  ingress:
    host: "rte.testing.star.eniblock.fr"
  credentials:
    secret: UilWyfG8ibzjstGMigFjXdTC7yCDdFQ0
