ingress:
  enabled: true
  host: "rte.staging.star.eniblock.fr"
backend:
  peerConnectionOrganization: rte
  instance: tso
keycloak:
  ingress:
    host: "rte.staging.star.eniblock.fr"
  credentials:
    secret: RtaW4iLCJJc3N1ZXIiOiJJc3N
